name: Build
on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_TEST_THREADS: "1"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.3
      - uses: pre-commit/action@v3.0.1

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        feature: ["ilp64,sequential", "lp64,sequential"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.feature }}
      - name: Build
        run: cargo build -vv --no-default-features -F "${{ matrix.feature }}"
